//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot.Dictionaries {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotDictionary() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot.Dictionaries.BotDictionary", typeof(BotDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправь мне свою группу, *русскими буквами*. Например, ИТ-01..
        /// </summary>
        internal static string AskGroup {
            get {
                return ResourceManager.GetString("AskGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для начала напиши мне своё ФИО..
        /// </summary>
        internal static string AskUserFullName {
            get {
                return ResourceManager.GetString("AskUserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Команда, *{0}*, не найдена.
        /// </summary>
        internal static string CommandNofFound {
            get {
                return ResourceManager.GetString("CommandNofFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты успешно зарегистрирован. 
        ///
        ///{0} ({1}).
        /// </summary>
        internal static string RegistrationCommandRegistrationComplete {
            get {
                return ResourceManager.GetString("RegistrationCommandRegistrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО не корректное.
        /// </summary>
        internal static string RegistrationCommandUserSentIncorrentFullName {
            get {
                return ResourceManager.GetString("RegistrationCommandUserSentIncorrentFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа не корректная.
        /// </summary>
        internal static string RegistrationCommandUserSentIncorrentGroup {
            get {
                return ResourceManager.GetString("RegistrationCommandUserSentIncorrentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет, {0}..
        /// </summary>
        internal static string StartCommandForRegisteredUser {
            get {
                return ResourceManager.GetString("StartCommandForRegisteredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет. 
        ///
        ///Для того чтобы начать работу с ботом тебе нужно зарегистрироваться. Чтобы продолжить нажми на кнопку..
        /// </summary>
        internal static string StartCommandForUnregisteredUser {
            get {
                return ResourceManager.GetString("StartCommandForUnregisteredUser", resourceCulture);
            }
        }
    }
}
